### ISSUE TITLE
Problem while parsing the package

### ISSUE THREAD

**Issue by repercussion** [Citrus-CAF/packages_apps_Margarita#1]
Lineage 14.1 on an LG H830 can't install any of the apks provided as they all have parsing errors. This is the first apk I've run across that will not install.

**Comment by Adarsh-MR** [comment]
Its due to minSdk set to api27 (android-8.1) and its intentionally done to prevent users apply on unsupported android version.

**Comment by repercussion** [comment]
Lovely. Thanks. See you when I get a phone with oreo builds!

**Comment by wilmarcdw** [comment]
Ah, but I'm also getting parsing errors for the apk on both Cardinal and AOSiP Oreo 8.1.0 ROMs on my Moto G5s Plus. [Oops, just realized this issue is from months ago].

Parsing error is for the new version 7.0.0 apk. Is that one api28 only? Changelog says support for Pie but doesn't say it is for Pie only.

**Comment by Adarsh-MR** [comment]
yes sorry, it's for pie only
